require "../spec_helper"
require "./upstream_support"

include UpstreamSupport

describe "Parser upstream parity (types and literals)" do
  it_parses "def foo(x : Foo?, y : Foo::Bar | Baz) : Foo(Int32)?\nend"
  it_parses "def foo(& : Int32 -> Nil) : Int32 -> Nil; end"
  it_parses "def foo(x : (Int32, Float64) -> Nil); end"
  it_parses "def foo(x : -> Nil); end"
  it_parses "{foo: 1} {\"a\" => 2}"
  it_parses "x : {Foo, Bar}"
  it_parses "x : {foo: Bar}"
  it_parses "x : Int32[8]"
  it_parses "x : Int32[8]?"
  it_parses "x : Foo*"
  it_parses "x : Foo**"
  it_parses "a : Foo"
  it_parses "a : Foo | Int32"
  it_parses "@a : Foo"
  it_parses "@a : Foo | Int32"
  it_parses "@@a : Foo"
  it_parses "a : Foo = 1"
  it_parses "@a : Foo = 1"
  it_parses "@@a : Foo = 1"
  it_parses "Foo?"
  it_parses "a : Foo()?"
  it_parses "a : Foo()*"
  it_parses "a : Foo()[12]"
  it_parses "a : Foo?"
  it_parses "a : Foo*"
  it_parses "a : Foo[12]"
  it_parses "a : Foo ->"
  it_parses "a : Foo -> Bar"
  it_parses "a = uninitialized Foo; a"
  it_parses "@a = uninitialized Foo"
  it_parses "@@a = uninitialized Foo"
  it_parses "::A::B"
end
