require "../spec_helper"
require "./upstream_support"

extend UpstreamSupport

describe "Parser upstream parity (structures and visibility)" do
  it_parses "class Foo; end"
  it_parses "class Foo\nend"
  it_parses "class Foo\ndef foo; end; end"
  it_parses "annotation Foo; end"
  it_parses "annotation Foo\n\nend"
  it_parses "annotation Foo::Bar\n\nend"
  it_parses "module Foo; end"
  it_parses "module Foo\ndef foo; end; end"
  it_parses "struct Foo; end"
  it_parses "enum Foo; end"
  it_parses "lib LibC; end"
  it_parses "union Foo; end"
  it_parses "abstract class Foo; end"
  it_parses "abstract struct Foo; end"
  it_parses "abstract module Foo; end"

  it_parses "class Foo < Bar; end"
  it_parses "struct Foo < Bar :Qux end"
  it_parses "class Foo(T); end"
  it_parses "class Foo(T1); end"
  it_parses "class Foo(Type); end"
  it_parses "module Foo(*T); end"
  it_parses "class Foo(*T); end"
  it_parses "class Foo(T, *U); end"
  it_parses "class Foo < self; end"
  it_parses "struct Foo include Bar end"
  it_parses "struct Foo :Bar end"
  it_parses "struct Foo :bar end"
  it_parses "struct Foo 'a' end"
  it_parses "struct Foo [1] end"
  it_parses "struct Foo {1} end"
  it_parses "struct Foo ->{} end"
  it_parses "struct Foo ->(x : Bar){} end"
  it_parses "struct Foo %w() end"
  it_parses "struct Foo %() end"
  it_parses "module Foo(T); end"
  it_parses "alias Name = Int32"
  it_parses "type Name = Int32"

  it_parses "private def foo; end"
  it_parses "protected def foo; end"
  it_parses "private macro foo; end"

  it_parses "class Foo; property bar; end"
  it_parses "class Foo; getter bar; end"
  it_parses "class Foo; setter bar; end"
  it_parses "class Foo; property bar : Int32; end"
  it_parses "def initialize(@x : Int32); end"
  it_parses "a = 1; class Foo; @x = a; end"
  it_parses "class Foo include Bar end"
  it_parses "class Foo < Bar :Qux end"
  it_parses "class Foo \"a\" end"
  it_parses "class Foo 'a' end"
  it_parses "class Foo [1] end"
  it_parses "class Foo {1} end"
  it_parses "class Foo ->{} end"
  it_parses "class Foo ->(x : Bar){} end"
  it_parses "class Foo :Bar end"
  it_parses "class Foo :bar end"
  it_parses "class Foo %x() end"
  it_parses "class Foo %w() end"
  it_parses "class Foo %() end"
  it_parses "struct Foo %x() end"
  it_parses "module Foo %x() end"
  it_parses "module Foo 'a' end"
  it_parses "module Foo [1] end"
  it_parses "module Foo {1} end"
  it_parses "module Foo ->{} end"
  it_parses "module Foo ->(x : Bar){} end"
  it_parses "module Foo :Bar end"
  it_parses "module Foo :bar end"
  it_parses "module Foo %w() end"
  it_parses "module Foo %() end"
  it_parses "module Foo include Bar end"
end
