require "../spec_helper"
require "./upstream_support"

include UpstreamSupport

describe "Parser upstream parity (types and literals)" do
  it_parses "def foo(x : Foo?, y : Foo::Bar | Baz) : Foo(Int32)?\nend"
  it_parses "def foo(& : Int32 -> Nil) : Int32 -> Nil; end"
  it_parses "def foo(x : (Int32, Float64) -> Nil); end"
  it_parses "def foo(x : -> Nil); end"
  it_parses "{foo: 1} {\"a\" => 2}"
  it_parses "x : {Foo, Bar}"
  it_parses "x : {foo: Bar}"
  it_parses "x : Int32[8]"
  it_parses "x : Int32[8]?"
  it_parses "x : Foo*"
  it_parses "x : Foo**"
  it_parses "a : Foo"
  it_parses "a : Foo | Int32"
  it_parses "@a : Foo"
  it_parses "@a : Foo | Int32"
  it_parses "@@a : Foo"
  it_parses "a : Foo = 1"
  it_parses "@a : Foo = 1"
  it_parses "@@a : Foo = 1"
  it_parses "Foo?"
  it_parses "a : Foo()?"
  it_parses "a : Foo()*"
  it_parses "a : Foo()[12]"
  it_parses "a : Foo?"
  it_parses "a : Foo*"
  it_parses "a : Foo[12]"
  it_parses "a : Foo ->"
  it_parses "a : Foo -> Bar"
  it_parses "a = uninitialized Foo; a"
  it_parses "@a = uninitialized Foo"
  it_parses "@@a = uninitialized Foo"
  it_parses "::A::B"
  it_parses "Foo::Bar"
  it_parses "Foo::Bar?"
  it_parses "Foo(T)?"
  it_parses "Foo()?"
  it_parses "Foo??"
  it_parses "x : Foo(A, *B, C)"
  it_parses "x : *T -> R"
  it_parses "def foo(x : *T -> R); end"
  it_parses "Foo()"
  it_parses "Foo(T)"
  it_parses "Foo(T | U)"
  it_parses "Foo(Bar(T | U))"
  it_parses "Foo(Bar())"
  it_parses "Foo(T?)"
  it_parses "Foo(1)"
  it_parses "Foo(T, 1)"
  it_parses "Foo(T, U, 1)"
  it_parses "Foo(T, 1, U)"
  it_parses "Foo(X, sizeof(Int32))"
  it_parses "Foo(X, instance_sizeof(Int32))"
  it_parses "Foo(X, alignof(Int32))"
  it_parses "Foo(X, instance_alignof(Int32))"
  it_parses "Foo(X, offsetof(Foo, @a))"
  it_parses "Foo(*T)"
  it_parses "Foo(\n)"
  it_parses "Foo(\nT\n)"
  it_parses "Foo(\nT,\nU,\n)"
  assert_syntax_error "Foo(X\n,Y)"
  it_parses "Foo(typeof(1))"
  it_parses "Foo(typeof(1), typeof(2))"
  it_parses "Foo({X, Y})"
  it_parses "Foo({X, Y,})"
  it_parses "Foo({*X, *{Y}})"
  it_parses "Foo({->})"
  it_parses "Foo({String, ->})"
  it_parses "Foo({String, ->, ->})"
  it_parses "Foo(x: U)"
  it_parses "Foo(x: U, y: V)"
  assert_syntax_error "Foo(x: X\n,y: Y)"
  it_parses "Foo(X: U, Y: V)"
  assert_syntax_error "Foo(T, x: U)"
  assert_syntax_error "Foo(x: T y: U)"
  assert_syntax_error "Foo(\"\": T)"
  it_parses %(Foo("foo bar": U))
  it_parses %(Foo("foo": U, "bar": V))
  it_parses "Foo({x: X})"
  it_parses "Foo({x: X, y: Y})"
  it_parses "Foo({X: X, Y: Y})"
  it_parses "Foo(T, {x: X})"
  it_parses "Foo({x: X, typeof: Y})"
  it_parses %(Foo({"foo bar": X}))
  it_parses %(Foo({"foo": X, "bar": Y}))
  it_parses "Foo(\nx:\nT,\ny:\nU,\n)"
  it_parses "[] of {String, ->}"
  it_parses "x([] of Foo, Bar.new)"
  it_parses "Foo(_)"
end
