require "../spec_helper"
require "./upstream_support"

include UpstreamSupport

describe "Parser upstream parity (regex and globals)" do
  it_parses "/foo/"
  it_parses "/foo/i"
  it_parses "/foo/m"
  it_parses "/foo/x"
  it_parses "/foo/imximx"
  it_parses "/fo\\so/"
  it_parses "/fo\#{1}o/"
  it_parses "/(fo\#{\"bar\"}\#{1}o)/"
  it_parses "%r(foo(bar))"
  it_parses "/ /"
  it_parses "/=/"
  it_parses "/ hi /"
  it_parses "self / number"
  it_parses "a == / /"
  it_parses "/ /; / /"
  it_parses "/ /\n/ /"
  it_parses "a = / /"
  it_parses "(/ /)"
  it_parses "a = /=/"
  it_parses "a; if / /; / /; elsif / /; / /; end"
  it_parses "a; if / /\n/ /\nelsif / /\n/ /\nend"
  it_parses "a; unless / /; / /; else; / /; end"
  it_parses "a\nunless / /\n/ /\nelse\n/ /\nend"
  it_parses "a\nwhile / /; / /; end"
  it_parses "a\nwhile / /\n/ /\nend"
  it_parses "[/ /, / /]"
  it_parses "{/ / => / /, / / => / /}"
  it_parses "{/ /, / /}"
  it_parses "begin; / /; end"
  it_parses "begin\n/ /\nend"
  it_parses "/\\//"
  it_parses "/\\ /"
  it_parses "%r(/)"
  it_parses "%r(\\/)"
  it_parses "%r(\\ )"
  it_parses "a()/3"
  it_parses "a() /3"
  it_parses "a.b() /3"
  it_parses "def foo(x = / /); end"
  it_parses "begin 1 end / 2"
  it_parses "1 =~ 2"
  it_parses "1.=~(2)"
  it_parses "def =~; end"
  it_parses "foo /a/"
  it_parses "foo(/a/)"
  it_parses "foo(//)"
  it_parses "foo(regex: //)"
  it_parses "foo(/ /)"
  it_parses "foo(/ /, / /)"
  it_parses "foo a, / /"
  it_parses "foo /;/"

  it_parses "$~"
  it_parses "$~.foo"
  it_parses "$0"
  it_parses "$1"
  it_parses "$1?"
  it_parses "foo $1"
  it_parses "$~ = 1"
  it_parses "$?"
  it_parses "$?.foo"
  it_parses "foo $?"
  it_parses "$? = 1"

  assert_syntax_error "$0 = 1", "global match data cannot be assigned to"
  assert_syntax_error "$0, $1 = [1, 2]", "global match data cannot be assigned to"
  assert_syntax_error "$0, a = {1, 2}", "global match data cannot be assigned to"
  assert_syntax_error "$2147483648"
  assert_syntax_error "$99999999999999999999999?", "Index $99999999999999999999999 doesn't fit in an Int32"
end
