require "../spec_helper"
require "./upstream_support"

include UpstreamSupport

describe "Parser upstream parity (enums and aliases)" do
  it_parses "enum Color\n  Red\n  Green\n  Blue\nend"
  it_parses "enum Flag\n  A = 1\n  B = 2\nend"
  it_parses "enum Foo; A\nB; C\nD = 1; end"
  it_parses "enum Foo; A = 1; B; end"
  it_parses "enum Foo : UInt16; end"
  it_parses "enum Foo : UInt16 ; end"
  it_parses "enum Foo : UInt16 # comment\nend"
  it_parses "enum Foo; def foo; 1; end; end"
  it_parses "enum Foo; A = 1\ndef foo; 1; end; end"
  it_parses "enum Foo; A = 1\ndef foo; 1; end\ndef bar; 2; end\nend"
  it_parses "enum Foo; A = 1\ndef self.foo; 1; end\nend"
  it_parses "enum Foo::Bar; A = 1; end"
  it_parses "enum Foo; @@foo = 1\n A \n end"
  it_parses "alias Name = Int32"
  it_parses "type Name = Int32"
  it_parses "enum X; @[Foo]; Bar; end"
  it_parses "enum X; private def foo; end; end"
  it_parses "enum X; protected macro foo; end; end"
  it_parses "enum Foo; private def foo; 1; end; end"
  it_parses "enum Foo; protected def foo; 1; end; end"
  it_parses "enum Foo; {{1}}; end"
  it_parses "enum Foo; {% if 1 %}2{% end %}; end"
  it_parses "enum Foo; macro foo;end; end"
  it_parses "enum Foo; @[Bar]; end"

  assert_syntax_error "enum Foo; A B; end"
  assert_syntax_error "enum Foo\n  A,   B,   C\nend\n"
  assert_syntax_error "enum Foo < UInt16; end"
end
