module Facet
  module Compiler
    module Keywords
      TABLE = {
        "abstract"         => TokenKind::KeywordAbstract,
        "alias"            => TokenKind::KeywordAlias,
        "alignof"          => TokenKind::KeywordAlignof,
        "annotation"       => TokenKind::KeywordAnnotation,
        "as"               => TokenKind::KeywordAs,
        "as?"              => TokenKind::KeywordAsQuestion,
        "asm"              => TokenKind::KeywordAsm,
        "begin"            => TokenKind::KeywordBegin,
        "break"            => TokenKind::KeywordBreak,
        "case"             => TokenKind::KeywordCase,
        "class"            => TokenKind::KeywordClass,
        "def"              => TokenKind::KeywordDef,
        "do"               => TokenKind::KeywordDo,
        "else"             => TokenKind::KeywordElse,
        "elsif"            => TokenKind::KeywordElsif,
        "end"              => TokenKind::KeywordEnd,
        "ensure"           => TokenKind::KeywordEnsure,
        "enum"             => TokenKind::KeywordEnum,
        "extend"           => TokenKind::KeywordExtend,
        "false"            => TokenKind::KeywordFalse,
        "for"              => TokenKind::KeywordFor,
        "fun"              => TokenKind::KeywordFun,
        "if"               => TokenKind::KeywordIf,
        "in"               => TokenKind::KeywordIn,
        "include"          => TokenKind::KeywordInclude,
        "instance_alignof" => TokenKind::KeywordInstanceAlignof,
        "instance_sizeof"  => TokenKind::KeywordInstanceSizeof,
        "is_a?"            => TokenKind::KeywordIsAQuestion,
        "lib"              => TokenKind::KeywordLib,
        "macro"            => TokenKind::KeywordMacro,
        "module"           => TokenKind::KeywordModule,
        "next"             => TokenKind::KeywordNext,
        "nil"              => TokenKind::KeywordNil,
        "nil?"             => TokenKind::KeywordNilQuestion,
        "of"               => TokenKind::KeywordOf,
        "offsetof"         => TokenKind::KeywordOffsetof,
        "out"              => TokenKind::KeywordOut,
        "property"         => TokenKind::KeywordProperty,
        "getter"           => TokenKind::KeywordGetter,
        "setter"           => TokenKind::KeywordSetter,
        "pointerof"        => TokenKind::KeywordPointerof,
        "private"          => TokenKind::KeywordPrivate,
        "protected"        => TokenKind::KeywordProtected,
        "require"          => TokenKind::KeywordRequire,
        "rescue"           => TokenKind::KeywordRescue,
        "responds_to?"     => TokenKind::KeywordRespondsToQuestion,
        "return"           => TokenKind::KeywordReturn,
        "select"           => TokenKind::KeywordSelect,
        "self"             => TokenKind::KeywordSelf,
        "sizeof"           => TokenKind::KeywordSizeof,
        "struct"           => TokenKind::KeywordStruct,
        "super"            => TokenKind::KeywordSuper,
        "then"             => TokenKind::KeywordThen,
        "true"             => TokenKind::KeywordTrue,
        "type"             => TokenKind::KeywordType,
        "typeof"           => TokenKind::KeywordTypeof,
        "uninitialized"    => TokenKind::KeywordUninitialized,
        "union"            => TokenKind::KeywordUnion,
        "unless"           => TokenKind::KeywordUnless,
        "until"            => TokenKind::KeywordUntil,
        "verbatim"         => TokenKind::KeywordVerbatim,
        "when"             => TokenKind::KeywordWhen,
        "while"            => TokenKind::KeywordWhile,
        "with"             => TokenKind::KeywordWith,
        "yield"            => TokenKind::KeywordYield,
      } of String => TokenKind

      def self.lookup(bytes : Bytes, start : Int32, length : Int32) : TokenKind?
        TABLE[String.new(bytes[start, length])]?
      end
    end
  end
end
